In [1]:
import numpy as np

# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입
<br>
행렬 (2,6) <br>
2개를 만들면 (2,2,6) => shape <br>
2행 6행짜리 매트릭스를 2개 쌓은것 <br>
ndim은 3차원 : 사유, 6 1차 2 2차 2 3차 <br>

## 1.1 배열 생성

### 1.1.1 기본 배열 생성

In [39]:
a = list(range(10))
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [4]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0, 10) + 1
np.arange(0, 10) * 3
np.arange(0, 10) / 2
np.arange(0, 10) - 1
# 모든 연산 계산가능

1~100 등수 순서 무작위로 나열 <br>
1~20등 => 1등급 <br>
21~40등 => 2등급 <br>
... <br>
80등~100등 => 5등급 <br>

In [25]:
ranks = np.random.choice(np.arange(1,101), size=100)

In [26]:
grades = []
for rank in ranks :
    if rank > 80 :
        grades.append(5)
    elif rank > 60 :
        grades.append(4)
    elif rank > 40 :
        grades.append(3)
    elif rank > 20 :
        grades.append(2)
    else :
        grades.append(1)

In [27]:
ranks

array([ 43,  80,  57,  77,  93,   2,  70,  88,  84, 100,  55,  24,  28,
        75,  10,  38,  48,  88,  98,  13,  95,  77,  61,  32,  74,  65,
        14,  23,  76,  23,   7,  40,  62, 100,  66,  22,  23,  46,  95,
        33,  66,   9,  25,  10,  82,  35,  46,  89,  87,  80,  78,  67,
        36,  30,  76,  65,  76,  89,  22,  52,   3,  72,  96,   3,  23,
        62,  15,  65,  88,   8,  99,  45,  86,  33,  59,  58,  34,  41,
        54,  92,  26,  37,   2,  46,   7,   5,   3,  72,   2,  49,   4,
        12,  18,  34,  45,  73,  84,  48,  12,  31])

In [ ]:
grades

In [29]:
ranks.sort()

In [31]:
ranks[:20] = 1
ranks[20:40] = 2
ranks[40:60] = 3
ranks[60:80] = 4
ranks[80:] = 5

In [32]:
ranks

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
ranks = np.random.choice(np.arange(1,101), size=100)
((ranks-1)//20) + 1

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [40]:
np.linspace(2, 3, num=5) #2부터 3까지를 5개로 나누기

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

#### eye(항등행렬)

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5) #shape 5짜리 0
x = np.zeros((5, 2), dtype=float)
```

In [41]:
print(np.zeros((3,5,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [48]:
np.full(5, np.inf)
np.full((5, 2), np.nan)

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [51]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [55]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [52]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [53]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim , 앞 포함/ 뒷미포함
```

In [59]:
# 함수만들기
# input 돈
# output 몇장 당첨

from tqdm import tqdm

def lotto(money, win_numbers):
    numbers = np.random.randint(0,46,size=(money//1000, 6))
    win_count = 0

    for number in tqdm(numbers) :
        number.sort()

        if list(number) == win_numbers :
            win_count += 1
    
    return win_count


#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [ ]:
np.random.normal(loc=0, scale=10, size=(5,2))

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br> concatenate 역연산
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3) #동일한 개수로 나눠야함. 2로나누면 에러
np.split(x, [3, 5, 6, 10])
```

In [60]:
x = np.arange(9)
print(np.split(x,3))
print(np.split(x, [3,5,6,10])) #인덱스로 자를 구간

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([], dtype=int32)]


### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [61]:
x = np.arange(10)
np.roll(x, 2) #2칸 밀어버림

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [67]:
x = np.arange(20).reshape(4, 5)
print(x)
print("--------------")
print(np.flip(x, axis=0))
print("--------------")
print(np.flip(x, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
--------------
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
--------------
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


In [69]:
x[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [ ]:
x = np.random.randint(0, 10, (5, 4))
print(x)
print("---------------")
x.sort(axis=0)
print(x)
print("---------------")
x.sort(axis=1)
print(x)

#### argsort : 인덱스반환

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [73]:
x = np.random.randint(0, 10, 10)
print(x)
print(np.unique(x))

[9 5 2 9 4 7 6 4 7 4]
[2 4 5 6 7 9]


#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환(에러처리) <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(x, trim='f')    # 앞의 0만 제거
np.trim_zeros(x, trim='b')    # 뒤의 0만 제거
np.trim_zeros(x, trim='fb')   # 앞뒤 0 제거
```

stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [74]:
x = np.arange(10)
print()
print(np.lib.stride_tricks.sliding_window_view(x, 3))


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [75]:
x = np.random.randint(0,10,size=(2,3))
print(x)
print('--------------------')
print(np.argmax(x))
print('--------------------')
print(np.argmax(x, axis=0)) #아래위로 비교. 위가 0 밑이 1
print('--------------------')
print(np.argmax(x, axis=1)) #행끼리만 비교

[[5 4 9]
 [6 3 8]]
--------------------
2
--------------------
[1 0 0]
--------------------
[2 2]


### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [77]:
x = np.random.randint(1,10,10)
print(x)
print(x[np.where(x<5)])
print(np.where(x<5,1,0))

[6 1 6 1 9 7 3 8 6 7]
[1 1 3]
[0 1 0 1 0 0 1 0 0 0]


### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [80]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))
print(x)
print(y)
print(x*y)
print(x@y)

[[3 1]
 [5 1]]
[[8 2]
 [7 4]]
[[24  2]
 [35  4]]
[[31 10]
 [47 14]]


### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [86]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
print(np.linalg.eig(x))

[[6 4]
 [2 2]]
(array([7.46410162, 0.53589838]), array([[ 0.9390708 , -0.59069049],
       [ 0.34372377,  0.80689822]]))


### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [89]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
print(np.linalg.det(x))

[[8 5]
 [2 3]]
13.999999999999996


### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```